port = PORT
listen_addresses = '127.0.0.1'
unix_socket_directories = 'TMP_DIR/PORT'

logging_collector = on
log_directory = 'TMP_DIR/PORT/data'
log_filename = 'pg.log'
log_rotation_age = 0
log_rotation_size = 0
log_min_duration_statement = 0

shared_buffers = 32MB
fsync = off
max_wal_size = 128MB
min_wal_size = 32MB

wal_level = replica
max_wal_senders = 10
max_replication_slots = 10
hot_standby = on
